services:
  toonflow:
    image: ghcr.io/yueyefengs/toonflow-app:latest
    platform: linux/amd64
    container_name: toonflow
    restart: unless-stopped
    ports:
      - "10588:10588"
    volumes:
      - ./data:/app/data
